# Generated by Django 2.2.1 on 2019-11-04 09:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trade_id', models.UUIDField()),
                ('size', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('receivable', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('tp_tid', models.CharField(max_length=128)),
                ('oln_item_id', models.CharField(max_length=128)),
                ('oln_status', models.IntegerField(default=0)),
                ('oln_sku_id', models.CharField(max_length=128)),
                ('status', models.IntegerField(default=0)),
                ('orders_id', models.CharField(max_length=128)),
                ('oln_item_name', models.CharField(max_length=256)),
                ('has_refund', models.IntegerField(default=0)),
                ('tp_oid', models.CharField(max_length=128)),
                ('is_gift', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trades',
            fields=[
                ('trade_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=128)),
                ('shop_nick', models.CharField(max_length=128)),
                ('storage_name', models.CharField(max_length=128)),
                ('storage_code', models.CharField(max_length=128)),
                ('trade_no', models.CharField(max_length=128)),
                ('buyer_msg', models.CharField(max_length=128)),
                ('oln_status', models.IntegerField(default=0)),
                ('buyer_account', models.CharField(max_length=128)),
                ('buyer', models.CharField(max_length=128)),
                ('receiver', models.CharField(max_length=128)),
                ('phone', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('province', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('district', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('create_time', models.DateTimeField()),
                ('modify_time', models.DateTimeField()),
                ('pay_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.IntegerField(default=0)),
                ('is_pay', models.BooleanField(default=False)),
                ('is_exception_trade', models.BooleanField()),
                ('tp_tid', models.CharField(max_length=128)),
                ('source_platform', models.CharField(max_length=128)),
                ('sum_sale', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('post_fee', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('paid_fee', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('discount_fee', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('has_refund', models.BooleanField()),
                ('oln_order_list', models.CharField(max_length=128)),
                ('is_small_trade', models.BooleanField()),
                ('process_status', models.IntegerField(default=0)),
                ('trade_type', models.IntegerField(default=0)),
                ('mark', models.CharField(max_length=512)),
                ('flag', models.IntegerField(default=0)),
                ('pay_no', models.CharField(max_length=128)),
                ('pay_type', models.CharField(max_length=128)),
                ('currency_code', models.CharField(max_length=128)),
                ('currency_sum', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
            ],
        ),
    ]
