# Generated by Django 2.2.1 on 2019-11-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0002_orders_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='seller_msg',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='trades',
            name='zip',
            field=models.CharField(default='', max_length=64),
        ),
    ]
