# Generated by Django 2.2.1 on 2019-11-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0003_auto_20191107_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='trades',
            name='send_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='create_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='modify_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='trades',
            name='pay_time',
            field=models.DateTimeField(null=True),
        ),
    ]
