# Generated by Django 2.2.1 on 2019-11-07 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0004_auto_20191107_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsSpec',
            fields=[
                ('spec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bar_code', models.CharField(max_length=128, null=True, verbose_name='条码')),
                ('item_name', models.CharField(max_length=512, null=True, verbose_name='商品名称')),
                ('spec_code', models.CharField(max_length=128, null=True, verbose_name='规格编码')),
                ('color', models.CharField(max_length=128, null=True, verbose_name='颜色')),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='标价')),
                ('article_number', models.CharField(max_length=128, null=True, verbose_name='货号')),
                ('item_code', models.CharField(max_length=128, null=True, verbose_name='商品编码')),
                ('category', models.CharField(max_length=128, null=True, verbose_name='品类')),
                ('brand', models.CharField(max_length=256, null=True, verbose_name='品牌名称')),
                ('other_prop', models.CharField(max_length=256, null=True, verbose_name='其他规格')),
                ('unit', models.CharField(max_length=128, null=True, verbose_name='单位')),
                ('prop1', models.CharField(max_length=256, null=True, verbose_name='自定义规格')),
                ('prop2', models.CharField(max_length=256, null=True, verbose_name='自定义规格')),
                ('prop3', models.CharField(max_length=256, null=True, verbose_name='自定义规格')),
            ],
        ),
    ]
