# Generated by Django 2.2.1 on 2019-11-08 17:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0006_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supplier_code', models.CharField(max_length=256, null=True, verbose_name='供应商编码')),
                ('supplier_name', models.CharField(max_length=256, null=True, verbose_name='供应商名称')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
        ),
    ]
