# Generated by Django 2.2.1 on 2019-11-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0007_supplier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoodsSpec',
            new_name='Specs',
        ),
    ]
