# Generated by Django 2.2.1 on 2019-11-11 16:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0008_auto_20191111_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=256, null=True, verbose_name='品牌名称')),
                ('category_name', models.CharField(max_length=128, null=True, verbose_name='分类')),
                ('expiration', models.IntegerField(default=0, verbose_name='保质期')),
                ('goods_code', models.CharField(max_length=128, null=True, verbose_name='商品编码')),
                ('goods_name', models.CharField(max_length=512, null=True, verbose_name='商品名称')),
                ('manufacturer_name', models.CharField(max_length=256, null=True, verbose_name='生产商')),
                ('pic', models.CharField(max_length=512, null=True, verbose_name='商品图片')),
                ('purchase_num', models.FloatField(default=0, verbose_name='采购数量')),
                ('purchase_type_name', models.CharField(max_length=128, null=True, verbose_name='采购类型')),
                ('remark', models.CharField(max_length=512, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsSpecs',
            fields=[
                ('goods_spec_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bar_code', models.CharField(max_length=128, null=True, verbose_name='条码')),
                ('spec_code', models.CharField(max_length=128, null=True, verbose_name='规格编码')),
                ('height', models.FloatField(default=0, verbose_name='高度')),
                ('length', models.FloatField(default=0, verbose_name='长度')),
                ('width', models.FloatField(default=0, verbose_name='宽度')),
                ('weight', models.FloatField(default=0, verbose_name='重量')),
                ('pic', models.CharField(max_length=512, null=True, verbose_name='图片')),
                ('prime_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='参考进价')),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='标准售价')),
                ('wholesale_price', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='批发价')),
                ('spec1', models.CharField(max_length=256, null=True, verbose_name='规格1值')),
                ('spec2', models.CharField(max_length=256, null=True, verbose_name='规格2值')),
            ],
        ),
    ]
