# Generated by Django 2.2.1 on 2019-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0009_goods_goodsspecs'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsspecs',
            name='goods_code',
            field=models.CharField(max_length=128, null=True, verbose_name='商品编码'),
        ),
        migrations.AddField(
            model_name='goodsspecs',
            name='goods_id',
            field=models.UUIDField(null=True),
        ),
    ]
