# Generated by Django 2.2.1 on 2019-11-12 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timedTask', '0014_auto_20191112_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestockdetails',
            name='sale_stock_id',
            field=models.UUIDField(null=True, verbose_name='出库单UUID'),
        ),
    ]
